include(ExternalProject)
set(CANGJIE_DEMANGLER_CMAKE_ARGS
    -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
    -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
    -DCMAKE_SYSROOT=${CMAKE_SYSROOT}
    -DBUILD_GCC_TOOLCHAIN=${BUILD_GCC_TOOLCHAIN}
    -DCMAKE_INSTALL_PREFIX=${CMAKE_BINARY_DIR}/cangjie-demangler
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE})

set(CANGJIE_DEMANGLER_CONFIGURE_COMMAND
    ${CMAKE_COMMAND} <SOURCE_DIR> -G${CMAKE_GENERATOR} ${CANGJIE_DEMANGLER_CMAKE_ARGS})
ExternalProject_Add(
    cangjie-demangler
    SOURCE_DIR ${CMAKE_SOURCE_DIR}/src/Demangle
    CONFIGURE_COMMAND ${CANGJIE_DEMANGLER_CONFIGURE_COMMAND}
    BUILD_COMMAND ${CMAKE_COMMAND} --build .
    INSTALL_COMMAND ${CMAKE_COMMAND} --install .)
